### ISSUE TITLE
Kino outside of LiveBook?

### ISSUE THREAD

**Issue by thbar** [livebook-dev/kino#100]
I am finding myself using LiveBook for data exploration more and more, and at one point a question comes up: how to move my findings & code into a backoffice page.

Typically: I have found something insightful via exploration, and would like to easily convert that to something that is a part of our app.

I wonder if Kino could be used outside of LiveBook easily? Or if there are plans to make this easy?

Thanks!

**Comment by josevalim** [comment]
For VegaLite itself you can export it and load it into any page by clicking the top right button. Is that not enough?

**Comment by thbar** [comment]
Sorry - reading your message I realised that my main current interest is in Kino itself (in particular, `Kino.DataTable`) ; I envision that I will also use VegaLite more later, but I can remove it from the issue name for now! (I have not enough feedback of use to determine my thinking on VegaLite export yet).

**Comment by josevalim** [comment]
There are no plans for this. Making it work within another web application would require reimplementing tons of Livebook features we don't plan to work on at the moment. However, we do want to allow you to export widgets from Livebook and you can embed them via JS or run them in their own page. :)

**Comment by jonatanklosko** [comment]
For the reference, VegaLite is not tied to Kino, so apart from export you can also use it within your app. [Here](https://github.com/jonatanklosko/vega_lite_lv_example) is an example of doing that with LiveView.

**Comment by thbar** [comment]
Ok, thanks for the clarifications to both of you! These are useful informations!
