### ISSUE TITLE
Print supervision trees

### ISSUE THREAD

**Issue by josevalim** [livebook-dev/kino#154]
If a process represents a supervisor (based on Process.info and Supervisor.which_children), we  can use Kino.Markdown with Mermaid to print the supervision tree. For example:

```mermaid
graph TD
    A(#PID<0.23.3>) --> B(Foo.Bar.Sup)
    B ---> C(Foo.Baz.Sup)
    C --->D(One)
    C --->E(#PID<1.2.3>)
    C --->F(Three)
    B -.->F
    style A stroke-width:3px
```

The root has a different stroke to mark the initial PID. Dotted lines can used for links.

**Comment by josevalim** [comment]
Another idea is `Kino.Process.trace/2`:

```
Kino.Process.trace(pid, fn ->

end)
```

The above will trace all messages received by `pid` (or list of pids) and build a sequence diagram.

**Comment by akoutmos** [comment]
I am getting close to opening a PR for this but had a question regarding links. Should a process with a link to another process in a separate supervision tree be added to the graph? Or should links that are only present between children of the root supervisor be drawn out? (hopefully that question makes sense)

Also, how do you feel about color coding supervisors versus workers?

![image](https://user-images.githubusercontent.com/4753634/175759983-0dfa16a7-13ad-4924-aa41-63397623da64.png)

**Comment by josevalim** [comment]
Exciting!!!!

Only links between processes already in the tree which _are not_ direct children. So in your case, no links between children and their parents, but a link between 0.271.0 and 0.269.0.

**Comment by josevalim** [comment]
Btw, let's call the module `Kino.Process`. :)
