### ISSUE TITLE
`Kino.Input.read` does not get the current value when used inside `Kino.VegaLite.periodically`

### ISSUE THREAD

**Issue by PhillippOhlandt** [livebook-dev/kino#167]
I wanted to use a checkbox to control what is happening inside a `Kino.VegaLite.periodically` but `Kino.Input.read` always returns the value that was set when the iteration started.

These are the Livebook code cells:

```elixir
frame = Kino.Frame.new()
```

```elixir
checkbox = Kino.Input.checkbox("My Checkbox")
```

```elixir
Kino.VegaLite.periodically(frame, 1000, 1, fn i ->
  IO.inspect Kino.Input.read(checkbox )

  {:cont, i + 1}
end)
```

If run as is, the initial checkbox value will be `false` which will be printed to the output. Toggling the checkbox does not reflect in the new output.

**Comment by josevalim** [comment]
This is correct. The values are not propagated to the cells until the cells are reevaluated. I think you can change this by using `Kino.Control.stream(...)` passing the checkbox and the interval, and calling Kino.VegaLite push API to update the chart: https://hexdocs.pm/kino/Kino.Control.html#stream/1
