### ISSUE TITLE
Let number of rows per page be configurable for DataTable

### ISSUE THREAD

**Issue by kevinlang** [livebook-dev/kino#175]
When using `Kino.DataTable` in livebook, it will only show 10 rows at a time. This should be configurable.

As far as I can tell it is hardcoded to 10 here. https://github.com/livebook-dev/kino/blob/5d9bee0da23aedc1ebd859659f968552fda5d6dc/lib/kino/table.ex#L48

**Comment by josevalim** [comment]
Yes, we are going to redesign data tables sooner than later, and we plan to make this configurable.
