### ISSUE TITLE
Kino.DataTable.new does not support Explorer Dataframes or structs

### ISSUE THREAD

**Issue by aedwardg** [livebook-dev/kino#178]
Passing an Explorer DataFrame to `Kino.DataTable.new` results in the following error:

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for #Explorer.DataFrame<
...
> of type Explorer.DataFrame (a struct). This protocol is implemented for the following type(s): Date.Range, Explorer.PolarsBackend.DataFrame, Explorer.PolarsBackend.Series.Iterator, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream, Table.Mapper, Table.Zipper
    (elixir 1.13.4) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.13.4) lib/enum.ex:199: Enumerable.slice/1
    (elixir 1.13.4) lib/enum.ex:4213: Enum.slice_any/3
    (elixir 1.13.4) lib/enum.ex:437: Enum.at/3
    (kino 0.6.2) lib/kino/data_table.ex:104: Kino.DataTable.infer_count/2
    (kino 0.6.2) lib/kino/data_table.ex:56: Kino.DataTable.new/2
```

This is surprising because the Explorer DataFrame implements the Table.Reader protocol, so it's reasonable to expect DataFrames to work here. Piping the dataframe to `DataFrame.to_columns/2` first is not a great workaround since you lose the ordering of the columns when doing so.

I'm not sure if this is high priority though, given the work done in #42. If that PR will still take a while to move forward, however, it might be nice to fix this in the meantime.

I'm quite new to Elixir, but I wouldn't mind trying my hand at a solution if this project is accepting public PRs.

**Comment by josevalim** [comment]
It is a Kino bug. We are assuming that all tables are also enuremables. :)
