### ISSUE TITLE
UUID's in a smart cell chart do not work

### ISSUE THREAD

**Issue by the-destro** [livebook-dev/kino#192]
## Current behavior

1) query a simple table with UUID's with, say, a count and grouping by the id field
2) Create a chart that tries to use UUID's on the x axis
3) Get Error `Failed to serialize initial widget data, invalid byte 0xC0 in <<uuid binary redacted>>`

## Expected behavior

No Error

![Screen Shot 2022-08-26 at 10 30 41 AM](https://user-images.githubusercontent.com/11051278/186929111-778f4f32-0c37-4675-b0f7-8f1edc16352f.png)

**Comment by josevalim** [comment]
Notice this happens both on Kino.VegaLite but also on Kino.DataTable.

**Comment by jonatanklosko** [comment]
@josevalim we can't serialize arbitrary binaries into JSON, so isn't this expect for UUIDs in the raw binary format?

**Comment by josevalim** [comment]
@jonatanklosko we can actually encode, but I think the client really dislikes it:

```
iex(2)> Jason.encode <<0, 1, 2>>
{:ok, "\"\\u0000\\u0001\\u0002\""}
```

**Comment by jonatanklosko** [comment]
```
iex> Jason.encode(Ecto.UUID.bingenerate())
{:error,
 %Jason.EncodeError{
   message: "invalid byte 0xAA in <<170, 141, 85, 72, 103, 180, 79, 91, 166, 160, 104, 128, 6, 179, 246, 193>>"
 }}
```

**Comment by josevalim** [comment]
Oh, I see. And because of #180 the error only happens later, so it is a bit harder to provide earlier feedback?

**Comment by jonatanklosko** [comment]
I think #180 doesn't change much in this specific case as there is no struct involved, so we would get the same error on either side. If we want a more specific error message we would need to match on `%Jason.EncodeError{message: "invalid byte" <> _}`.

**Comment by josevalim** [comment]
With #180 I was thinking we would at least get an error from Kino and have it show up with stacktrace?

**Comment by josevalim** [comment]
In any case, this can be closed. We might improve things with #180.

**Comment by jonatanklosko** [comment]
> With https://github.com/livebook-dev/kino/issues/180 I was thinking we would at least get an error from Kino and have it show up with stacktrace?

Note that the serialization happens on demand, when someone connects to the component and it would be inside the Kino.JS.Live server, so I'm not sure if the stacktrace will be helpful. But maybe there's a way to show more relevant information, we can revisit :)

**Comment by 03juan** [comment]
@the-destro did you manage to work around this issue?

This is practically the only page that comes up when searching for this error message so for anyone interested I solved this by explicitly casting the UUID to `varchar` in the kino_db smartcell query. Unfortunately it forced me to be explicit in the select statement and not just `select *` but rather `select id::varchar, relation_id::varchar, inserted_at` etc...

Hope this helps.
