### ISSUE TITLE
Support a list of assets in `Kino.JS` `:assets_path`

### ISSUE THREAD

**Issue by jonatanklosko** [livebook-dev/kino#196]
So it is easier to reuse files across kinos.

**Comment by aleDsz** [comment]
I was thinking about that yesterday, where we could serve the assets from Kino and other users could create their SmartCells with these assets from `kino`

**Comment by jonatanklosko** [comment]
For #289 we need assets to point to a single directory, so I would close this one.

I feel if we want better sharing long term it would make more sense to just use something like esbuild and simply bundle things as needed.
