### ISSUE TITLE
Application.ensure_all_started(:kino) required in Attached mode?

### ISSUE THREAD

**Issue by kipcole9** [livebook-dev/kino#201]
[Vix](https://github.com/akash-akya/vix) has [added support for the Kino.Render protocol](https://github.com/akash-akya/vix/blob/master/lib/vix/vips/image.ex#L697-L724) which is working well.

But I notice that when running in attached mode with Kino 0.7 (since there is no longer a `mix` standalone mode) that rendering will fail unless `Application.ensure_all_started :kino` is added to the notebook or `:kino` is added to `:extra_applications` in `mix.exs`.

If this is expected behaviour then I'll send a documentation PR.

**Comment by josevalim** [comment]
Yes, you either need to start Kino in the notebook or have it started. But there is a replacement for Mix standalone that is not attached mode, which are the new options in Mix.install. Check the Elixir and Livebook notebook. :)
