### ISSUE TITLE
Getting stuck when trying to download a large file

### ISSUE THREAD

**Issue by petrkozorezov** [livebook-dev/kino#204]
```elixir
Mix.install([{:kino, "~> 0.6"}])
```
```elixir
Kino.Download.new(
  fn -> :binary.copy(<<42>>, 200 * 1024 * 1024) end,
  filename: "test.data"
)
```

**Comment by jonatanklosko** [comment]
Hey @petrkozorezov, it works for me, are you running the latest version of Livebook?

**Comment by petrkozorezov** [comment]
> Hey @petrkozorezov, it works for me, are you running the latest version of Livebook?

Oh, thanks! I will check my installation.
