### ISSUE TITLE
Kino.Download not working

### ISSUE THREAD

**Issue by tricoiret** [livebook-dev/kino#207]
I have a notebook in which I attempt to download a csv using Kino. 

I am running this code: `Kino.Download.new(fn -> "a, b, c" end)`.The first time I run it, it produces a download button, that does nothing when clicked. Subsequently, reevaluating the cell gives the message `Output data no longer available, please reevaluate this cell`. reevaluating it again prints the following error message:
```
09:55:44.433 [error] GenServer Kino.Terminator terminating
** (FunctionClauseError) no function clause matching in Kino.Terminator.handle_info/2
    (kino 0.7.0) lib/kino/terminator.ex:27: Kino.Terminator.handle_info({:terminate, #PID<0.201.0>}, %{})
    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
    (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:terminate, #PID<0.201.0>}
State: %{}
```

I am using Livebook 0.6.3, Kino 0.7.0 and Elixir 1.13.4, running on windows 11.

**Comment by jonatanklosko** [comment]
Hey @tricoiret, please try Livebook v0.7.0 :)

**Comment by tricoiret** [comment]
It worked, thank you!
