### ISSUE TITLE
Kino.Datatable javascript main.js asset load issue

### ISSUE THREAD

**Issue by lexlapax** [livebook-dev/kino#214]
I'm using Elixir 1.14.1 on MacOS 12.6.1 installed via macbrew. 
Running Livebook 0.7.0 via escript install. 
I get javascript asset/path issue with Datatable..
attached screenshots..

I've tried running livebook via mix, also the latest from github.. same issue.
![image](https://user-images.githubusercontent.com/381394/204149177-b7349730-fa93-442b-9d9b-40cc010a8b62.png)

![image](https://user-images.githubusercontent.com/381394/204149164-6a4b9fb5-48f2-431d-a8a8-99dfb34290fc.png)

![image](https://user-images.githubusercontent.com/381394/204149153-f4ea90e6-5c1a-4211-92a6-165cf2f0adcc.png)

Thoughts on this?

**Comment by josevalim** [comment]
Please update to latest Livebook. There was a bug on macOS related to temporary system directories.
