### ISSUE TITLE
Adding kino as a dependency to project "breaks" dbg/2

### ISSUE THREAD

**Issue by teamon** [livebook-dev/kino#228]
I've been using livebook connected to a remote live app. In order to get access to kino I've added it as a dependency in `mix.exs`. After doing that, I've lost output from `dbg/2` calls, both in development and in test.

Is this expected behaviour? 
If so, should there be some warning about it?

UPDATE: 
I've figured this is due to kino doing this:

https://github.com/livebook-dev/kino/blob/2ef471de853ba2a8526a6e64fcb26c44ec2c0145/lib/kino/application.ex#L7

**Comment by josevalim** [comment]
Yeah, maybe we should detect if we are inside Livebook before doing this? Any suggestion on how to do this detection @jonatanklosko? We could check for a module... but iirc they are all private? Alternatively we could use an env var.

**Comment by teamon** [comment]
💜 💜 💜
