### ISSUE TITLE
ETS with Kino.DataTable broken?

### ISSUE THREAD

**Issue by BrooklinJazz** [livebook-dev/kino#244]
I've encountered an issue where `:ets` tables that used to display nicely in DockYard Academy don't anymore. https://github.com/DockYard-Academy/curriculum/issues/710.

![image](https://user-images.githubusercontent.com/14877564/214014076-5cc0676b-3979-4001-b0ec-fe6cfb7e3f47.png)
If I remember correctly, the key and the value of the inserted record used to be in their own column, but now it's squished into one column called "row".

It also seems like empty tables can no longer display. It will flash for a moment, then disappear. 

![image](https://user-images.githubusercontent.com/14877564/214014343-5f865d29-19d8-4a90-8bfd-dfaa1754afb2.png)

I can create a new table, insert an element, then render it, and it works fine though.

![image](https://user-images.githubusercontent.com/14877564/214014402-3c21d32d-a486-4c59-a2b4-c55ea112e8d5.png)

I'm using kino `0.8` and livebook `0.8`. Am I doing something wrong, or can others reproduce this issue? Thank you!

**Comment by josevalim** [comment]
The moving to `row` is expected because `ets` rows don't have a predetermined size, unfortunately. However, I think we should expand the whole row if there is space and empty tables should not flash. Thanks for the report. :)

**Comment by BrooklinJazz** [comment]
Absolutely. Will test and verify.

**Comment by BrooklinJazz** [comment]
@cristineguadelupe Yup! Verified it's working. Feel free to close.

The row is still squished, but I think that's a livebook problem, not a kino problem.

Should I raise an issue there?

**Comment by josevalim** [comment]
Squished row is fixed by #247.
