### ISSUE TITLE
Issue with Kino.Input.number & Firefox

### ISSUE THREAD

**Issue by maxxst** [livebook-dev/kino#278]
The Arrows of the Number Input are not recognized (at least in Firefox).
Keyboard Arrow Up and Down Works.

![ezgif-3-e7ea99b486](https://user-images.githubusercontent.com/570654/232833968-47f9b9f9-e36a-4097-8419-2cbe437db7ee.gif)

## Update 

I just checked it in Chrome and there it is working

**Comment by jonatanklosko** [comment]
We use `phx-debounce="blur"`, so the change is reflected when the input is focused, changed and blurred. In other browsers hitting the up/down arrows focuses the input, so it is blurred on submit as expected. In Firefox however, hitting up/down doesn't change focus and it looks like a [known bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1012818) (or at least known behaviour). So this applies to LV in general, cc @chrismccord.

**Comment by josevalim** [comment]
Closing this a known firefox bug. :(
