### ISSUE TITLE
`Kino.animate/2` does not work properly in `0.9.2` version

### ISSUE THREAD

**Issue by gabrielpedepera** [livebook-dev/kino#280]
Following the notebook [Deploy a chat app with Kino](https://github.com/livebook-dev/livebook/blob/main/lib/livebook/notebook/learn/deploy_apps.livemd) I faced the issue:

```
19:25:31.047 [error] GenServer #PID<0.682.0> terminating
** (stop) exited in: GenServer.call(#PID<0.682.0>, {:render, %Kino.Markdown{content: "**Iteration: `0`**"}, :default}, 5000)
    ** (EXIT) process attempted to call itself
    (elixir 1.14.2) lib/gen_server.ex:1031: GenServer.call/3
    (kino 0.9.2) lib/kino.ex:295: anonymous fn/3 in Kino.animate/3
    (kino 0.9.2) lib/kino/frame.ex:208: Kino.Frame.periodically_iter/3
    (kino 0.9.2) lib/kino/frame.ex:178: Kino.Frame.handle_cast/2
    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
    (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:periodically, 100, {0, nil}, #Function<1.16875015/1 in Kino.animate/3>}}
State: %{outputs: [], ref: "-576460752303422390"}

** (exit) exited in: GenServer.call(#PID<0.682.0>, :get_outputs, 5000)
    ** (EXIT) exited in: GenServer.call(#PID<0.682.0>, {:render, %Kino.Markdown{content: "**Iteration: `0`**"}, :default}, 5000)
        ** (EXIT) process attempted to call itself
    (elixir 1.14.2) lib/gen_server.ex:1038: GenServer.call/3
    (kino 0.9.2) lib/kino/render.ex:64: Kino.Render.Kino.Frame.to_livebook/1
    (kino 0.9.2) lib/kino.ex:164: Kino.render/1
    (kino 0.9.2) lib/kino.ex:306: Kino.animate/3
    #cell:5fz77cxxqrhs3ormvfuo62pyxobbeuv4:1: (file)
```

<img width="990" alt="image" src="https://user-images.githubusercontent.com/384201/233858333-415309ea-0158-41d7-938d-a2a4104cae50.png">

Perhaps the https://github.com/livebook-dev/kino/pull/277 changes could have introduced a side effect in the `Kino.animate/2` function.

**Comment by jonatanklosko** [comment]
Oh this is a side effect of #277. When interval ms is given to `Kino.animate` we use `Kino.Frame.periodically` and then `Kino.Frame.render` inside, which never returns because `periodically` blocks it.

https://github.com/livebook-dev/kino/blob/4a5a17d2e95fd3d9eef4b2a5ff6cbab59377b1e3/lib/kino.ex#L289-L295

We can either use listen instead of periodically, as we do for the general stream case. Or we need a different solution for #277. @josevalim thoughts?

**Comment by josevalim** [comment]
Yeah, :+1: for moving the periodically out of the frame. We should probably kill periodically altogether.

**Comment by gabrielpedepera** [comment]
Sorry for jumping into it. 😅 I was trying to understand your comments, but not sure if I get right. So forgive me for any possible misunderstanding.

To get rid of the periodically implementation and use the listen approach we would need to abstract the Stream.interval(100) |> Stream.take(100) into the animate/3, right?
