### ISSUE TITLE
Rendering Kino.nothing in a frame or layout prints `:"do not show this result in output"` 

### ISSUE THREAD

**Issue by mat-hek** [livebook-dev/kino#292]
Kino version: 0.9.4
Livebook version: 0.9.2

To reproduce:

```elixir
frame = Kino.Frame.new()
Kino.Frame.render(frame, Kino.nothing())
frame
```

I'm currently using `nothing = Kino.Markdown.new("")` as a workaround

**Comment by jonatanklosko** [comment]
Hey @mat-hek, this is expected, `Kino.nothing()` is specifically for cases where the cell evaluation result shouldn't be added as a final inspect output. The magic atom it returns matches IEx for consistency.

A frame is already empty by default and you can remove its contents with `Kino.Frame.clear/1`. I assume you want to get rid of the "Nothing here..." placeholder, correct? With the current APIs I would use `Kino.Frame.render(frame, Kino.Layout.grid([]))`.

@josevalim we could have a `:placeholder` option to disable the default box, wdyt?

**Comment by josevalim** [comment]
An option sounds great to me.

**Comment by jonatanklosko** [comment]
I wonder if it should be `placeholder: true | false` (defaults to `true`) or `placeholder: String.t() | nil` (defaults to `"Nothing here..."`). The latter is more flexible, but it is kinda weird to allow `nil` and default to string at the same time.

**Comment by mat-hek** [comment]
> I assume you want to get rid of the "Nothing here..." placeholder, correct?

Yeah, that's the primary case, but it's also handy when I have a function like

```elixir
def generate_some_kino(params) do
  if ... do
    # create some actual kino
  else
    # return nothing
  end
end
```

as I can simply call `Kino.Frame.render(generate_some_kino(params))`.

It also allows having an empty cell in a layout.

**Comment by jonatanklosko** [comment]
> as I can simply call `Kino.Frame.render(generate_some_kino(params))`.

You could define:

```elixir
defp update_frame(frame, nil), do: Kino.Frame.clear(frame)
defp update_frame(frame, kino), do: Kino.Frame.render(frame, kino)
```

Then use it to update the frame; this way you could skip the else branch in `generate_some_kino`.

> It also allows having an empty cell in a layout.

Semantically `Kino.nothing()` is not *empty output*, but *no output*. In case of layout the cell needs to be *something*, so I would do `defp blank(), do: Kino.Layout.grid([])` and use that instead.

**Comment by mat-hek** [comment]
Got it.

> defp blank(), do: Kino.Layout.grid([])

WDYT about `Kino.blank()`? :P

**Comment by jonatanklosko** [comment]
> WDYT about `Kino.blank()`? :P

I considered that, but I'm not sure, so I would defer until there are more use cases. @josevalim if you have preference let me know, alternatively we could add `Kino.blank()` and kill `Kino.nothing()` (or change the behaviour of `Kino.nothing()`).

**Comment by josevalim** [comment]
The reason we have nothing() is to mirror IEx. So given we have to support it forever, I don’t think it is worth changing. I am fine with checking nothing() inside frame though and then rendering nothing.

**Comment by jonatanklosko** [comment]
I added support for `Kino.Frame.new(placeholder: false)` in #297.

As for `Kino.nothing()` I really don't think we should special case the atom, and either way it's really about skipping output, not an empty space (e.g. in a grid).

We can always revisit if there are more use cases :)
