### ISSUE TITLE
Update example module name in smart cell docs

### ISSUE THREAD

**Issue by zachallaun** [livebook-dev/kino#301]
More of a reminder to myself to submit a PR later :)

Kino module docs recommend not using `Kino.` prefix for custom kinos: https://hexdocs.pm/kino/Kino.html#module-custom-kinos

Kino smart cell docs use `Kino.SmartCell.Custom` -- should rename to `CustomSmartCell` or similar.

**Comment by jonatanklosko** [comment]
Good catch, a PR is very welcome!
