### ISSUE TITLE
Show example images in the docs

### ISSUE THREAD

**Issue by tcoopman** [livebook-dev/kino#303]
Kino handles mostly with rendering input and output, and the docs always show code examples, but never how these outputs look like, making it sometimes hard to choose what you need exactly. 

It would be really useful to have images of how each rendered widget looks like in the docs.

**Comment by josevalim** [comment]
I am not sure, honestly. The best way to learn about those inputs is inside a Livebook and we already provide a Livebook for Kino. Adding images and keeping them in sync is additional work which we can focus on later.  :)

**Comment by tcoopman** [comment]
Where is that livebook for Kino? Can't find it in the docs/readme

**Comment by josevalim** [comment]
Inside Livebook there is a Learn section. Click on the left side of your sidebar. :)

**Comment by tcoopman** [comment]
Ok, this is embarrasing :-)

That documentation is indeed great. Not sure how how I missed that... I guess I immediately jumped into the Kino docs and didn't even read getting started.
