### ISSUE TITLE
Why Kino.listen doesn't return a pid?

### ISSUE THREAD

**Issue by jannikbecher** [livebook-dev/kino#305]
https://github.com/livebook-dev/kino/blob/78e58cfc4d8d4a7018644c55f9ba06b9100ff3ce/lib/kino.ex#L419-L428

Is there a specific reason why :ok is returned instead of the pid?
It would be nice to be able to do something like this:

```elixir
job_pid = Kino.listen(5000, fn i -> IO.puts(i) end)

Kino.Control.button("Kill job")
|> Kino.render()
|> Kino.listen(fn _ -> Process.exit(job_pid, :kill) end)
```

**Comment by josevalim** [comment]
Can you please send a PR?

**Comment by jannikbecher** [comment]
Just for reference:
`Process.exit(job_pid, :kill)` kills the whole cell. Instead use `Kino.terminate(job_pid)`
