### ISSUE TITLE
Customizing input size

### ISSUE THREAD

**Issue by lambdaofgod** [livebook-dev/kino#308]
I have a use case where default text box size is too small. Is it possible to customize it? How?

**Comment by josevalim** [comment]
Not currently possible. Should we support cols and rows as options for textarea?

**Comment by jonatanklosko** [comment]
@lambdaofgod isn't the textarea enough, or do you specifically need a text input that spans full width?

@josevalim the textarea is fullwidth and the rows expand automatically on enter. Though if it's a use case for other inputs we may want to support `full_width: true`.

**Comment by lambdaofgod** [comment]
Yeah I was thinking about something like full width. Now I see that textbox can be adjusted, that's good for now. Thanks!
