### ISSUE TITLE
Kino 11 giving error: Unknown output format

### ISSUE THREAD

**Issue by joshprintsimple** [livebook-dev/kino#354]
Hi, I've installed the latest livebook 10 and kino 11 on windows subsystem for linux and it's giving me an error when I install the dependencies, and for pretty much every block after that. Kino 10 works so I'm assuming I have everything installed properly but I still get this error:

Unknown output format: %{type: :terminal_text, text: "\e[34m:ok\e[0m", chunk: false}. If you're using Kino,
you may want to update Kino and Livebook to the latest version.

![image](https://github.com/livebook-dev/kino/assets/146996763/b4178d01-fe22-45bc-9d71-00eccf3daf33)

This stuff is amazing btw, I ended up getting the gpu working and I'm excited to try out Stable Diffusion, but since I have cuda 12, I need the latest version of kino to work for me. Thanks for everything you guys are doing!

**Comment by jonatanklosko** [comment]
See https://github.com/livebook-dev/livebook/issues/2259 :)
