### ISSUE TITLE
Changing sort column stays on the same page

### ISSUE THREAD

**Issue by LostKobrakai** [livebook-dev/kino#356]
When changing sort columns my expectation would be that the currently shown page would reset and not stay the same it was before.

**Comment by josevalim** [comment]
Can you be a bit more concrete or provide a small gif/video? What is the code/data? What page did you navigate to? How did you change the order?

**Comment by LostKobrakai** [comment]
Ah sorry. I'm querying a db using the kino smart cell and I'm talking about the table output kino provides (there and in other usecases). 

When I have a paginated result and go to e.g. page 3 and then hit a column heading to change the sort order the table view will stay on page 3. My expectation would be it going to page 1, when the sort order (or at least the sort column) is changed.

**Comment by josevalim** [comment]
Makes sense, thank you! PRs are also welcome!
