### ISSUE TITLE
Add callback to `Kino.interrupt!`

### ISSUE THREAD

**Issue by NduatiK** [livebook-dev/kino#367]
When using `Kino.interrupt!` it would be useful to be able to specify a task that should be executed before restarting the cell.

---

We're working on tutorials for Liveview Native in Livebook and would like to be able to interrupt execution if the default port is in use.
Assuming a `Port` module that can detect whether a port is in use and can also kill processes using a port, we'd like to be able to do the following:
```elixir
default_port = 4000

if HTTPPort.in_use?(default_port) do
  Kino.interrupt!(:error, "Input required", on_continue: {HTTPPort, :kill_process, [default_port]})
end

# Start Phoenix on port 4000
```

This addition will make it possible to interrupt execution whenever user confirmation is needed before performing an action. The current `interrupt!` does not allow developers to respond to a user clicking `Continue`.

What do you think? 

Let me know if you need someone to actually implement the change.

**Comment by josevalim** [comment]
At first I am :-1: because if you need to perform such tasks, it means you are generally unable to reevaluate the cell in the first place? Can you provide a more concrete example? Who is using that Port? Where and how was it started?

**Comment by NduatiK** [comment]
Sure thing. 

I mean that there is a system process somewhere that is making use of the HTTP port (not Elixir port 🙃).

Let's say that a new Elixir developer has run `mix phx.server` from their terminal.
If they attempts to start one of LiveView Native's tutorials, we would like to tell them that the port is in use and offer to kill the system process holding the port. 

The idea is that to block the execution until that system process is killed, and to offer the user a way to kill it.
`Kino.interrupt!` currently lets us block execution if some condition is not met. It would be nice to be able to execute some code before attempting to reevaluate the code.

**Comment by jonatanklosko** [comment]
@NduatiK you can do this:

```elixir
if Process.get(:port_taken?) do
  kill? = Kino.Shorts.read_checkbox("Kill port 4000")

  if kill? do
    Process.put(:port_taken?, true)
  else
    Kino.interrupt!(:normal, "Port 4000 is taken")
  end
end
```

Since you start the LVN server in the notebook, it would make sense to pick a more random port, so it's much less likely that people run into conflict :)

**Comment by NduatiK** [comment]
Thanks @jonatanklosko, we came up with a similar workaround, but yours is much cleaner.

Thanks!
