### ISSUE TITLE
Feature request: Multi-select

### ISSUE THREAD

**Issue by Munksgaard** [livebook-dev/kino#380]
The multi-select that is used in the data transformation smart cell when  "selecting" between outputs is very nice. Would it be possible to add something similar to `Kino.Control`?

**Comment by josevalim** [comment]
Right now we are sticking with HTML supported elements, but this is totally something we can consider in the future. Thank you!

**Comment by sergey-chechaev** [comment]
We really miss this feature. Maybe we'll reopen an issue
