### ISSUE TITLE
Kino.Layout.grid hangs forever when you pass another Kino to it

### ISSUE THREAD

**Issue by clayscode** [livebook-dev/kino#400]
<s>

```elixir  
Kino.Layout.grid(
   Kino.Control.form([
       a: Kino.Input.textarea("hello"), 
       b: Kino.Input.select("Test", [{"a","a"},{"b","b"},{"c","c"}])
    ],
   submit: "Submit")
)
```

Simple example, but if you run the above code, the cell will just keep evaluating for infinity. Probably using this wrong, but was just looking for a way to control my form's layout. 

Mix install:
```elixir
Mix.install([
  {:kino, "~> 0.12.3"},
])
```

If you just use input elements without the form, it evaluates fine:
```elixir
Kino.Layout.grid(
  [Kino.Input.textarea("test"), Kino.Control.button("Submit")]
)
```
Produces~
<img width="827" alt="Screenshot 2024-03-16 at 8 08 41 PM" src="https://github.com/livebook-dev/kino/assets/16871737/ccaddaa7-2de1-40cc-b863-7d5a1bf8f208"></s>

## Edit: Ah, forget all of that, this works fine:
```elixir
Kino.Layout.grid(
  [
   Kino.Control.form([
       a: Kino.Input.textarea("hello"), 
       b: Kino.Input.select("Test", [{"a","a"},{"b","b"},{"c","c"}])
    ],
   submit: "Submit")
  ]
)
```
I just forgot to call grid with a list. Still, shouldn't the correct behavior be to fail for just passing other Kino's? 
For instance:
```elixir
Kino.Layout.grid(
  Kino.Input.textarea("Hello")
)
``` 
This hangs forever
<img width="825" alt="Screenshot 2024-03-16 at 8 19 12 PM" src="https://github.com/livebook-dev/kino/assets/16871737/43da37be-1ffb-4abe-92f3-5719a3ac7c25">

**Comment by josevalim** [comment]
Yes, we should raise. The big question is how to do this: should we force it to be a list? Or should we continue to allow any enumerable but explicitly forbidden inputs? I am fine with adding a `is_list/1` guard.
