### ISSUE TITLE
Kino input field not appearing (bug?)

### ISSUE THREAD

**Issue by hugobarauna** [livebook-dev/kino#403]
When I run the following code in a code cell:

```elixir
Kino.Input.text("Node") |> Kino.render()
Kino.Input.text("Cookie") |> Kino.render()

Kino.nothing()
```

The output doesn't show the HTML input element of the first `Kino.Input`:

![CleanShot 2024-03-25 at 09 59 46](https://github.com/livebook-dev/kino/assets/2719/d0f2747f-a360-4b14-9274-f3c4d6516421)

I was able to replicate that bug with Livebook main, Kino main or Kino 0.12.3 (latest).

**Comment by jonatanklosko** [comment]
Fixed in https://github.com/livebook-dev/livebook/commit/c67095bbe12bcfd8fbc40d88875b343350e2d24f.
