### ISSUE TITLE
Custom Message in `Kino.Process.seq_trace`

### ISSUE THREAD

**Issue by mariari** [livebook-dev/kino#408]
It would be nice to be able to supply a function to `Kino.Process.seq_trace`, that can help augment the naming process.

For the code I work on, I see a lot of `CAST: tuple`, making the use of the utility of `seq_trace` limited.

This can be solved in a few ways:

1. Letting users write custom pattern matches for the kinds of messages they experience (much like how [label_from_message](https://github.com/livebook-dev/kino/blob/v0.12.3/lib/kino/process.ex#L422) already matches certain patterns).
2. Letting users supply their own custom `label_from_message` function to completely override the process.

I might try my hand at `1.` and contribute upstream if the idea works out.

**Comment by josevalim** [comment]
A custom label for messages function would be welcome indeed. Please do submit a PR :)
