### ISSUE TITLE
Add ETS table rendering to Kino.Process.{sup_tree,app_tree}

### ISSUE THREAD

**Issue by akoutmos** [livebook-dev/kino#430]
While working on the Elixir Patterns book I found it useful to include ETS tables in the `Kino.Process.sup_tree/1` rendering so readers could see the layout of process as well as any ETS tables associated with those processes. Something like so:

<img width="898" alt="image" src="https://github.com/livebook-dev/kino/assets/4753634/e802ebdc-18a6-4961-89bc-3bd1f94ff5a7">

If there is interest in adding this to Kino I can open up a PR with my work :).

**Comment by akoutmos** [comment]
Thanks!

1. Correct. The solid line to the ETS table is the owning process and the dotted line is the heir process.
2. good idea....I didn't even think about that. Do you picture it using Mermaid subgraphs?

**Comment by josevalim** [comment]
> Correct. The solid line to the ETS table is the owning process and the dotted line is the heir process.

I would invert the arrow then (perhaps annotate it with (heir) if possible.

> good idea....I didn't even think about that. Do you picture it using Mermaid subgraphs?

That would be the idea but I am not sure if it is better in practice.

**Comment by akoutmos** [comment]
Sounds good. I'll put together a couple hard coded mocks and post them here with which route we want to go.

**Comment by akoutmos** [comment]
Here are some hardcoded Mermaid diagrams for how we can render this:

Diagram without subgraph:
<img width="894" alt="image" src="https://github.com/livebook-dev/kino/assets/4753634/ec17e55c-54d5-4818-8339-a4a9d78daf04">

Diagram with subgraph:
<img width="896" alt="image" src="https://github.com/livebook-dev/kino/assets/4753634/8738b458-7d44-4ee4-aa95-0f429c24bc58">

We can also drop the arrows all together for ETS tables and label both owner and heir to be explicit
<img width="896" alt="image" src="https://github.com/livebook-dev/kino/assets/4753634/eedf2e0d-9be3-430d-9a46-58f04500593d">

Thoughts?

**Comment by josevalim** [comment]
I think the original one is less cluttered. I would only add an arrow to heir, but pointing to the process instead. What are your thoughts? Any thoughts @hugobarauna?

**Comment by akoutmos** [comment]
When the direction of the ETS owner edge changes, Mermaid shuffles the graph in a not so intuitive way:

<img width="889" alt="image" src="https://github.com/livebook-dev/kino/assets/4753634/50e74138-607d-4066-b636-f1330b5add9a">

**Comment by hugobarauna** [comment]
> I think the original one is less cluttered. I would only add an arrow to heir, but pointing to the process instead. What are your thoughts? Any thoughts @hugobarauna?

> I think the original one is less cluttered. 

Agree, without subgraphs. 

> I would only add an arrow to heir

From an educational point of view, maybe adding both "heir" and "owner" labels is a good direction.

For example, before that discussion, I didn't know an ETS table could have a relationship with two processes; I thought it was only related to one process. I just learned about the "heir" thing.

So, for someone like me (who is learning about ETS), if the diagram shows both labels, it can help me understand that an ETS table can have a relationship with two processes, one of which is the owner and the other the heir.

I'd keep both labels.

Regarding the arrows, the supervision diagram the way it is already has some implied semantics:

- an arrow from process A pointing to process B means that A supervises B
- a dotted line between two processes means they're linked (right? 🤔)

So, maybe we should use a different line from those two to imply a new semantic. Maybe just a simple line without arrows but with the "owner" or "heir" label.

**Comment by josevalim** [comment]
> I would only add an arrow to heir

Sorry, I was not clear. We should have both arrows, what I meant to say is that I would add an arrow to heir in addition to the label. Using arrows and labels in both is fine by me too. The reason I like the arrow in the heir case is because the "inheritance" happens by literally sending a message which transfers the table. The arrow in ownership is also important to say who owns who. For someone who is new, those relationships may not be clear, so I would emphasize them with arrows.

**Comment by akoutmos** [comment]
I think I got it lol. Reread all the comments a couple times and I'm pretty sure this is what you are both looking for:

<img width="893" alt="image" src="https://github.com/livebook-dev/kino/assets/4753634/388e729b-a985-4172-8e27-5ed730dd5aff">

**Comment by josevalim** [comment]
Sorry, the heir is from the table to the process. Everything else is perfect. :) Should we make the display of ETS tables opt-in or opt-out? Probably opt-in to avoid initial clutter?

**Comment by akoutmos** [comment]
Closing this as #432 was merged.
