### ISSUE TITLE
Support custom data formatter for Kino.DataTable

### ISSUE THREAD

**Issue by kipcole9** [livebook-dev/kino#440]
Currently `Kino.DataTable` formats data with either the `String.Chars` implementation or `inspect/2`.  However the default presentation isn't localizable or customisable - and since Livebooks can be targeted at a wider audience than just Elixir developers, an option to provide a formatter function would seem a good improvement to user experience.

The simplest option would be to add an optional formatter function to `Kino.DataTable.new/2`.  For example:
```elixir
Kino.DataTable.new(
  data,
  keys: [:registered_name, :initial_call, :reductions, :stack_size],
  formatter: &MyMod.formatter/2
)
```

The formatter function would receive the column value and the key so that formatting can be contextual. The default would be the current `value_to_string/1` function, slightly modified to accept (and ignore) the key.

If this idea is accepted I am very willing to create a PR. And of course if there is a better API thats good too.

**Comment by josevalim** [comment]
:+1:. @cristineguadelupe @jonatanklosko, do you foresee any issues?

**Comment by kipcole9** [comment]
I have made the necessary changes in [a fork of kino](https://github.com/kipcole9/kino) and implemented a livebook demonstrating an example using a formatter I built into a new release of [ex_cldr](https://hex.pm/packages/ex_cldr).  

[![Run in Livebook](https://livebook.dev/badge/v1/blue.svg)](https://livebook.dev/run?url=https%3A%2F%2Fraw.githubusercontent.com%2Felixir-cldr%2Fcldr%2Fv2.39.0%2Flivebook%2Fkino_data_table_formatting.livemd)

If you find the overall outcome acceptable I'll submit a PR. I'm unsure how to create tests for this change and I couldn't see any for the current implementation so I hope the example livebook is acceptable.

**Comment by josevalim** [comment]
I dropped some nits, it looks great to me :)

**Comment by josevalim** [comment]
Closing in favor of PR.
