### ISSUE TITLE
Integrated with VTable

### ISSUE THREAD

**Issue by fangsmile** [livebook-dev/kino#445]
Whether it can be integrated with VTable. VTable table library has a strong visual display ability and high-performance.
You can check the VTable website for more information：https://visactor.io/vtable
Github: https://github.com/VisActor/VTable

![img_v3_029n_c20f8bf0-914d-480e-9369-9541ff50bc7g](https://github.com/livebook-dev/kino/assets/3468473/0d7d44cc-bc4c-4b2d-892b-29c2bf933678)

**Comment by jonatanklosko** [comment]
The kino built-in table uses [Glide Data Grid](https://grid.glideapps.com), we have no plans to change that.

Depending on your use case, you can build a custom kino using `Kino.JS` and `Kino.JS.Live`, where you can use arbitrary JavaScript libraries, such as VTable :)
