### ISSUE TITLE
Kino not rendering graph, shows inspect result instead

### ISSUE THREAD

**Issue by vishal-h** [livebook-dev/kino#47]
On testing this code https://hexdocs.pm/kino/Kino.html#module-kino-datatable

On windows10/localhost shows the result as `%Kino.DataTable{pid: #PID<0.1496.0>}`

The same code, on cloud-vm/linux renders the vegalite correctly.

**Comment by josevalim** [comment]
I could not reproduce it on a Windows VM. What is the Livebook version in your Windows machine? You can find it in the /dashboard route or by doing `livebook —version`. It is most likely an old version that doesn’t support data tables yet.

**Comment by vishal-h** [comment]
I think that must be it. Windows had an old version running (0.1.0) and linux had the latest. 
It worked fine after getting the latest.
Thank you for the quick response!
