### ISSUE TITLE
[Feature Request] Allow passing number of rows to show in Kino.DataTable

### ISSUE THREAD

**Issue by tomekowal** [livebook-dev/kino#475]
Hi,

Thanks for the project. It is mind-blowingly fantastic! :)

I have a little nit about DataTable. I am using it for data set that is exactly 14 rows long.
When DataTable is first rendered, the default option is to show first 10 rows + pagination.
So, after each reevaluation, I need to click "show 20" to see everything.
(note that show: :all also does not solve the issue, because it adds scroll instead of pagination).
I would like to be able to pass initial values to `show` and `page` when initializing `DataTable`, e.g.

```
Kino.DataTable.new(data, keys: [:first_row, :second_row], show: 20, page: 1)
```

Alternatively, it could be nested:

```
Kino.DataTable.new(data, keys: [:first_row, :second_row], display_options: [show: 20, page: 1])
```

WDYT?

**Comment by jonatanklosko** [comment]
#476 added support for specifying custom number of rows. I'm not sure there's any value in specifying the page, the user could instead reorder their data.

**Comment by tomekowal** [comment]
Thank you! ❤️
