### ISSUE TITLE
Add Dynamic Image widget

### ISSUE THREAD

**Issue by zorbash** [livebook-dev/kino#48]
Hi Dashbit friends.

I am experimenting with a dynamic image widget and wondering whether it'd make sense to submit a pull request to have this be part of Kino / Livebook.

## Rationale

Initially I needed it show a video feed in one of my nerves notebooks with:

```elixir
video = fn y ->
  # Picam  captures stills using the camera module on Raspberry Pi
  Kino.Image.new(Picam.next_frame, :jpeg)
  |> Kino.render

  Process.sleep(100)
  y.(y)
end

video.(video)
```

My intention was to take a photo every 100ms, then update an image output cell with that image, but rendering `Kino.Image` appends a new image to the notebook instead.

There are though numerous use-cases, especially educational, where a dynamic image can be used with an `svg` to visualise an algorithm in an animated fashion. I'm am already working on visualising towers of hanoi and game of life.

## Demo

https://user-images.githubusercontent.com/645514/140661823-93b93bc0-ee0e-4389-9d07-0b3b6616a1a7.mp4

## Implementation

Currently, my implementation consists of a `LivebookWeb.Output.ImageLive` view in `livebook` and a `Kino.ImageDynamic` GenServer and minor changes in a few other files.

Please let me know your thoughts and thank you for Livebook and Kino 🙌

**Comment by josevalim** [comment]
Thank you @zorbash for the issue.

I am wondering if instead, we should introduce two new APIs:

1. One that clears the current output
2. Another for running things periodically

This way you can have a loop that clears the screen and adds the image, without it being image specific. :)

**Comment by zorbash** [comment]
I made a quick attempt to implement (1), which resulted in the following Livebook diff:

```diff
diff --git a/lib/livebook/evaluator/io_proxy.ex b/lib/livebook/evaluator/io_proxy.ex
index 5e290db..c4debf7 100644
--- a/lib/livebook/evaluator/io_proxy.ex
+++ b/lib/livebook/evaluator/io_proxy.ex
@@ -199,6 +199,14 @@ defmodule Livebook.Evaluator.IOProxy do
     {:ok, state}
   end

+  defp io_request(:livebook_clear_output, state) do
+    state = flush_buffer(state)
+    send(state.target, {:clear_evaluation_output, state.ref})
+
+    {:ok, state}
+  end
+
+
   defp io_request(_, state) do
     {{:error, :request}, state}
   end
diff --git a/lib/livebook/session.ex b/lib/livebook/session.ex
index 3818d47..cc78b5b 100644
--- a/lib/livebook/session.ex
+++ b/lib/livebook/session.ex
@@ -634,6 +634,11 @@ defmodule Livebook.Session do
     {:noreply, handle_operation(state, operation)}
   end

+  def handle_info({:clear_evaluation_output, cell_id}, state) do
+    operation = {:clear_cell_evaluation_output, self(), cell_id}
+    {:noreply, handle_operation(state, operation)}
+  end
+
   def handle_info({:evaluation_response, cell_id, response, metadata}, state) do
     operation = {:add_cell_evaluation_response, self(), cell_id, response, metadata}
     {:noreply, handle_operation(state, operation)}
diff --git a/lib/livebook/session/data.ex b/lib/livebook/session/data.ex
index 07f2044..db0bb50 100644
--- a/lib/livebook/session/data.ex
+++ b/lib/livebook/session/data.ex
@@ -393,6 +393,23 @@ defmodule Livebook.Session.Data do
     end
   end

+  def apply_operation(data, {:clear_cell_evaluation_output, _client_pid, id}) do
+    with {:ok, cell, _} <- Notebook.fetch_cell_and_section(data.notebook, id) do
+      data
+      |> with_actions()
+      |> set!(
+        notebook:
+          Notebook.update_cell(data.notebook, cell.id, fn
+            %Cell.Elixir{} = cell -> %{cell | outputs: []}
+            cell -> cell
+          end)
+      )
+      |> wrap_ok()
+    else
+      _ -> :error
+    end
+  end
+
```

and a `Kino.render/0`

```elixir
  def clear do
    gl = Process.group_leader()
    ref = Process.monitor(gl)

    send(gl, {:io_request, self(), ref, :livebook_clear_output})

    receive do
      {:io_reply, ^ref, :ok} -> :ok
      {:io_reply, ^ref, _} -> :error
      {:DOWN, ^ref, :process, _object, _reason} -> :error
    end

    Process.demonitor(ref)

    :"do not show this result in output"
  end
```



https://user-images.githubusercontent.com/645514/140752990-fe1b55c8-095c-4671-bdfe-8703a25ee7fd.mp4

It works, but _with my implementation_ the animation is not as smooth. Any pointers?

**Comment by jonatanklosko** [comment]
@zorbash I'm currently looking into a slightly different solution, will let you know how it goes soon!

**Comment by jonatanklosko** [comment]
I've just crated #49. With the new API the video feed would look like this:

```elixir
Kino.animate(100, :noop, fn acc ->
  img = Kino.Image.new(Picam.next_frame(), :jpeg)
  {:cont, img, acc}
end)
```

**Comment by zorbash** [comment]
Thank you @jonatanklosko that was quick and it looks like an elegant solution for my use-cases.

My only note is whether there should also be a `Kino.animate/2` where the `nil` initial value of the accumulator is implied, similar to how `Enum.reduce/2` doesn't need the initial value.

**Comment by jonatanklosko** [comment]
> My only note is whether there should also be a `Kino.animate/2` where the `nil` initial value of the accumulator is implied, similar to how `Enum.reduce/2` doesn't need the initial value.

Actually it was modeled similarly to `Enum.reduce_while/3`, which always requires the accumulator. `Enum.reduce/2` is quite different, because without the default value it just has different semantics. We could have a version without an accumulator at all, but passing the accumulator is not much work, so I'd stick to a single function for now :)

**Comment by jonatanklosko** [comment]
@zorbash we need to releasea new Kino and Livebook versions together, but with Livebook we are waiting for Elixir 1.13, so it may take a little bit. Feel free to try kino main alongside livebook main though :) And thanks for starting the discussion, I'm very happy with the result :cat:
