### ISSUE TITLE
UI bug when clicking column of data table with one row

### ISSUE THREAD

**Issue by hugobarauna** [livebook-dev/kino#480]
When I click a column of a data table that has only one row, more rows are "temporarily added" to the UI:

**Before clicking the column**

![CleanShot 2024-11-27 at 09 45 10](https://github.com/user-attachments/assets/5b489b90-7d5d-4839-a660-2701f3c5931f)

**After clicking the column**

![CleanShot 2024-11-27 at 09 45 53](https://github.com/user-attachments/assets/905483a7-9388-41f5-8088-4f451b6683bf)

**Comment by jonatanklosko** [comment]
We need to expand the iframe, but we can add extra space instead of table rows. Fixed in 2a7d598a593f4671819b625cac43066b57da8648.
