### ISSUE TITLE
Error when updated Elixir to 1.17 OTP 27

### ISSUE THREAD

**Issue by garlandcrow** [livebook-dev/kino#482]
After updating to elixir to 1.17 otp 27, I got an error when rendering a LiveView and then found livebook_get_evaluation_file wased using in `kino/bridge.ex` and so likely something to do with this new version. Removing Kino got rid of the error, but we use Kino in some of our livebooks. Maybe this is an easy fix?

```
[error] Process #PID<0.69.0> raised an exception
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(1, :livebook_get_evaluation_file)
    (kernel 10.2) group.erl:1281: :group.type/1
    (kernel 10.2) group.erl:1271: :group.log_io_request/3
    (kernel 10.2) group.erl:227: :group.io_request/6
    (kernel 10.2) group.erl:153: :group.server_loop/3
[error] GenServer #PID<0.64.0> terminating
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(1, :livebook_get_evaluation_file)
    (kernel 10.2) group.erl:1281: :group.type/1
    (kernel 10.2) group.erl:1271: :group.log_io_request/3
    (kernel 10.2) group.erl:227: :group.io_request/6
    (kernel 10.2) group.erl:153: :group.server_loop/3
Last message: {:EXIT, #PID<0.69.0>, {:badarg, [{:erlang, :element, [1, :livebook_get_evaluation_file], [error_info: %{module: :erl_erts_errors}]}, {:group, :type, 1, [file: ~c"group.erl", line: 1281]}, {:group, :log_io_request, 3, [file: ~c"group.erl", line: 1271]}, {:group, :io_request, 6, [file: ~c"group.erl", line: 227]}, {:group, :server_loop, 3, [file: ~c"group.erl", line: 153]}]}}
State: {:state, :user_sup, :undefined, #PID<0.69.0>, {#PID<0.64.0>, :user_sup}}
```

**Comment by jonatanklosko** [comment]
Hey @garlandcrow, can you provide an example to reproduce the error?

**Comment by garlandcrow** [comment]
Spent 4 hours trying to debug it bug so we give up and will just not use Kino anymore, so I'm oing to close it. It's a phoenix app generated a year ago and using Elixir 1.16. If I make a fresh phoenix app there is no issue. I don't know all the behind the scene stuff livebook is doing to somehow hook into a process but something isnt communicating correctly and 4hr is my limit to trying to dive through process trees and find out.

**Comment by jonatanklosko** [comment]
In which case does the bug appear? Are you using attached runtime, or installing your project as Mix.install dependency in the notebook? Does the error happen when calling a particular Kino API or adding dbg somewhere?

**Comment by garlandcrow** [comment]
Attached runtime. It happens with or without livebook running and with or without livebook being attached to the node and a livebook open. I can add Kino to other projects i have using Livebook and elixir 1.17 with no problem, so its some problem with a combination of things I have and not a general issue with Kino. I debugged every possible thing I could think of to no success. I checked w/ the person who added Kino initially and he said he did nothing special except at it as a dep.

Sorry, I should have researched more before filing an issue, I just figured it was some simple api change from 1.16 that could be easily fixed.

**Comment by jonatanklosko** [comment]
I was able to reproduce it. It appears when having kino as a dependency and using `dbg` combined with phoenix live reload (because modules are recompiled after kino registers its own `dbg` handler).

I believe it is actually a regression in OTP 27.2, I will open an issue/PR upstream.

On a sidenote, I wouldn't recommend having kino as a dependency. Instead, there are two other ways to interact with your Mix project:

1. Bring your project into the notebook via `Mix.install/2` as described [in this section](https://hexdocs.pm/livebook/use_cases.html#documentation-with-mix-install).

2. Use a plain notebook and use the Remote execution cell to evaluate code in the mix node (closer to an attached runtime).

In both cases the advantage is that you can bring any additional dependencies to the notebook, for smart cells, charts and whatnot.

**Comment by garlandcrow** [comment]
Thanks for the info and looking into it! Glad it wasn't a superfluous that I filed and will move those depa to be inside the Livebook. Thanks again for the help!
